name: Bot Auto Merge

on:
  # make workflow reusable, thus callable from other repositories
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'nuxeo-platform-jx-bot'
    steps:
    - name: Print workflow information
      run:
        echo Author = ${{ github.actor }}
    - name: Dependabot metadata
      id: metadata
      if: github.actor == 'dependabot[bot]'
      uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2.5.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Approve bot PRs
      if: |
        github.actor == 'nuxeo-platform-jx-bot'
        || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        || steps.metadata.outputs.update-type == 'version-update:semver-patch'
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Enable auto-merge for bot PRs
      if: |
        github.actor == 'nuxeo-platform-jx-bot'
        || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        || steps.metadata.outputs.update-type == 'version-update:semver-patch'
      run: gh pr merge --auto --rebase "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
